### ISSUE TITLE
ValueError: Captcha

### ISSUE THREAD

**Issue by Krylanc3lo** [VeNoMouS/cloudflare-scrape-js2py#24]
Hello!

A new day & a new CF error :)

I will investigate when I will be backi to home tonight but if anyone already saw this issue:

```
Traceback (most recent call last):
  File "/home/maxx/bin/dl_scripts/tv_list_page.py", line 39, in <module>
    data = getPage().getpage_text(sys.argv[2])
  File "/home/maxx/bin/dl_scripts/CF_getPage.py", line 35, in getpage_text
    if (True, True) == self._cloudFlare(ret, urlpage):
  File "/home/maxx/bin/dl_scripts/CF_getPage.py", line 20, in _cloudFlare
    if cf.is_cloudflare_challenge(response):
  File "/usr/local/lib/python3.6/dist-packages/cfscrape-2.0.3-py3.6.egg/cfscrape/__init__.py", line 64, in is_cloudflare_challenge
ValueError: Captcha
```

**Comment by HawkLiking** [comment]
This error means that cloudflare display a « captcha challenge », and cfscrape does not solve captcha challenges, only js challenges.

You should active Debug mode and paste the entire output here to see what is going on

**Comment by VeNoMouS** [comment]
https://github.com/VeNoMouS/cloudflare-scrape-js2py/issues/20#issuecomment-481199292

**Comment by leentheone** [comment]
Same problem. Earlier cfscrape just ignore this page, so I can solve the captcha and continue parse.

**Comment by VeNoMouS** [comment]
@leentheone so put it into a trap... and solve it on the exception whats the problem?

**Comment by leentheone** [comment]
> @leentheone so put it into a trap... and solve it on the exception whats the problem?

no problem, just module became less user-friendly

**Comment by pro-src** [comment]
@leentheone You do realize that cloudflare-scrape never raised an error for CAPTCHA so if you were using the older version then please realize the following.

* It would not be working at all (The old source was crap)
* You wouldn't know what the problem was to start with (The old source was crap)
* Thanks to the new version, you actually know that there is in fact a CAPTCHA
* There has many many improvements over the old source without regression.

So do you mind explaining why you think it became less user-friendly?

**Comment by Krylanc3lo** [comment]
Do you still have the issue ? I still experience it:

```
Traceback (most recent call last):
  File "/home/krylancelo/bin/dl_scripts/mangas_dl_japscan.py", line 38, in <module>
    data = getPage().getpage_text(sys.argv[2])
  File "/home/maxx/bin/dl_scripts/CF_getPage.py", line 35, in getpage_text
    if (True, True) == self._cloudFlare(ret, urlpage):
  File "/home/maxx/bin/dl_scripts/CF_getPage.py", line 23, in _cloudFlare
    response = cf.get(urlpage, timeout=15)
  File "/home/krylancelo/.local/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cfscrape-2.0.3-py3.6.egg/cfscrape/__init__.py", line 107, in request
  File "/usr/local/lib/python3.6/dist-packages/cfscrape-2.0.3-py3.6.egg/cfscrape/__init__.py", line 160, in solve_cf_challenge
  File "/usr/local/lib/python3.6/dist-packages/cfscrape-2.0.3-py3.6.egg/cfscrape/__init__.py", line 100, in request
  File "/usr/local/lib/python3.6/dist-packages/cfscrape-2.0.3-py3.6.egg/cfscrape/__init__.py", line 64, in is_cloudflare_challenge
ValueError: Captcha

```

**Comment by pro-src** [comment]
@Krylanc3lo are you using headers from your web browsers??? If not... that would be the first thing to try.

**Comment by Krylanc3lo** [comment]
I do not think I am. I am just using the script shared few days ago by @VeNoMouS . 

```
class getPage():
    def __init__(self):
            self.session = requests.session()
            self.funcName = lambda n=0: sys._getframe(n + 1).f_code.co_name + "()"
    
    
    def _cloudFlare(self, response, urlpage):
            cf = cfscrape.create_scraper(sess=self.session)
            cf.debug = True

    
            if cf.is_cloudflare_challenge(response):
                #print("{} requested URL - {}, encounted CloudFlare DDOS Protection.. Bypassing.".format(self.funcName(), response.url))
    
                response = cf.get(urlpage, timeout=15)
            
                if not cf.is_cloudflare_challenge(response):
                    return (True, True)
    
                return (True, False)
    
            return (False, True)
        
        
    def getpage(self, urlpage):
        ret = self.session.get(urlpage, timeout=15)
        if (True, True) == self._cloudFlare(ret, urlpage):
            #print("{} CloudFlare DDOS Protection.. Bypassed successfully.".format(self.funcName()))
            ret = self.session.get(urlpage, timeout=15)
        
        return ret.text
```

**Comment by pro-src** [comment]
I think @VeNoMouS plans on adding custom exception for the use-case that @leentheone mentioned. Even though he called it less user friendly just because it lacks a feature that he wants. It wasn't a feature in the old source... It was just by chance due to neglect... Anyways, you're not using headers from your web browser. Cloudflare has changed their Anti-Scrape shield a lot lately and we sympathize with you guys. The challenge is being solved correctly as of right now so the problem would be that Cloudflare has improved their filtering based on headers. The UA randomization is a problem... Until that gets fixed, always use headers from your own web browser. If you still get a CAPTCHA, we'll investigate it, provided that you supply us with a target. First things first, see if you get a CAPTCHA when using your web browser...

**Comment by pro-src** [comment]
@Krylanc3lo Also, I think the code in that snippet is a tad bit outdated in that it's doing things that aren't exactly necessary anymore. It looks like it should still work though...

**Comment by Krylanc3lo** [comment]
Thanks for the details, it is very helpful.
I will try to add the headers then. Can I do it in the code I did past above?

if there is an easier way to use the snippet, let me know and I will update my code.

Thanks  again

**Comment by pro-src** [comment]
@Krylanc3lo you're welcome :)

You should only need the following:
```py
cf = cfscrape.create_scraper()
cf.debug = True

def getPage(urlPage):
  return cf.get(urlpage, timeout=15)
```
Just keep a reference to `cf`(the scraper which is a session) and you don't even need `getPage`. You can just call `cf.get(urlPage, timeout=15)` directly when you need to fetch a page.

I haven't tested though. As far as passing headers: `cf.get(urlPage, headers=headers, timeout=15)` but use an `OrderedDict` because the header order matters.

**Comment by Krylanc3lo** [comment]
great thx @pro-src ! I will try it right now and let you know.
I just need to retrieve my browser headers

**Comment by Krylanc3lo** [comment]
Which headers should I take, the user agents or all of them ?

**Comment by pro-src** [comment]
@Krylanc3lo 

Any and all of the following:
* Connection
* User-Agent
* Upgrade-Insecure-Requests
* Accept
* Accept-Language
* Accept-Encoding
* DNT

If your `Accept-Encoding` header contains `br`, remove it.
For example: `"Accept-Encoding": "gzip, deflate, br"` would be changed to `"Accept-Encoding": "gzip, deflate"`

Pay close attention to the header order as well. Keep the original order that your browser has the headers in.

**Comment by Krylanc3lo** [comment]
Nevermind, with the new code it is working very well, I will not bother you more :)

Thanks a lot @VeNoMouS & @pro-src !

**Comment by pro-src** [comment]
@Krylanc3lo were you using an older version or do you mean your new code?

**Comment by Krylanc3lo** [comment]
Thank you. I will update my code with the headers & I used the below code you gave me : 

```
cf = cfscrape.create_scraper()
cf.debug = True

def getPage(urlPage):
  return cf.get(urlpage, timeout=15)
```

It is working better than my first version

How should I store the headers & delimit them ? in a json format ?

**Comment by VeNoMouS** [comment]
FWIW:

You don't need to keep the exact header order once you have solved the challenge...

**Comment by pro-src** [comment]
@Krylanc3lo VeNoMous has an example of using an OrderedDict to set the headers in the comment that he linked in his first post: https://github.com/VeNoMouS/cloudflare-scrape-js2py/issues/20#issuecomment-481199292

Only problem is that those headers will be ignored in some cases:
https://github.com/VeNoMouS/cloudflare-scrape-js2py/blob/83ebd10e678ef4a41cfda76389fd1befcc6d42c6/cfscrape/__init__.py#L79-L91

Namely if you set the headers on the `scraper` instance instead of passing them as a kwarg or if you set them when instantiating the class. Until that gets fixed you'll want to passing your headers as a kwarg every time you make a request.
